
version: 2
jobs:
  build:
    working_directory: ~/please
    docker:
      - image: thoughtmachine/please-servers:20200407
    steps:
      - checkout
      - restore_cache:
          key: go-linux-main-v4-{{ checksum "go.mod/" }}
      - run:
          name: Test
          command: ./pleasew test -p --profile ci -v 2
      - store_test_results:
          path: plz-out/results
      - run:
          name: Package
          command: ./pleasew build -v 2  -p --profile ci
      - run:
          name: Package Darwin
          command: ./pleasew build -a darwin_amd64 -v 2 -p --profile ci
      - persist_to_workspace:
          root: plz-out/bin
          paths:
            - wollemi
      - store_artifacts:
          path: plz-out/log
      - save_cache:
          key: go-linux-main-v4-{{ checksum "go.mod" }}
          paths: [ "go.mod" ]

  #  release:
  #    docker:
  #      - image: thoughtmachine/please_docs:20190318
  #    steps:
  #      - attach_workspace:
  #          at: /tmp/workspace
  #      - run: /tmp/workspace/scripts/gen_release.pex /tmp/workspace/elan/elan /tmp/workspace/flair/flair /tmp/workspace/mettle/mettle /tmp/workspace/zeal/zeal /tmp/workspace/lucidity/lucidity

workflows:
  version: 2
  build-all:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master